apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-policy-monitor
rules:
- apiGroups: ["image.toolkit.fluxcd.io"]
  resources: ["imagepolicies"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-policy-monitor
subjects:
- kind: ServiceAccount
  name: image-policy-monitor
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: image-policy-monitor
  apiGroup: rbac.authorization.k8s.io
