apiVersion: v1
kind: Service
metadata:
  name: image-policy-monitor
  namespace: monitoring
  labels:
    app: image-policy-monitor
spec:
  ports:
  - port: 2112
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: image-policy-monitor
